name: new workflow
on: [push]
jobs:
  pep8_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.7
    - name: install dependency
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        # установка зависимостей
        pip install -r requirements.txt 
 
    - name: test with flake
      run: |
        python -m flake8
        cd infra_project/
        # запустить написанные разработчиком тесты
        python manage.py test

  build_and_push:
    runs-on: ubuntu-latest
    needs: pep8_check
    steps:
    - name: check out
      uses: actions/checkout@v2
    - name: build docker image
      uses: docker/setup-buildx-action@v1
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ilyaart/website:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
    - name: ssh connect
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key:  ${{ secrets.SSH_KEY }}
        script: |
          sudo docker stop $(sudo docker ps -a -q)
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/website
          sudo docker run --rm -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/website